### ISSUE TITLE
Result is always 0

### ISSUE THREAD

**Issue by lacell75** [marcelblijleven/wdio-ms-teams-service#10]
Hello, thanks for this project but it doesn't work on my side.
The tests are executed with cucumber and the results displayed in teams is always 0:

```
Total tests 0
Passed 0
Failed 0
```

**Comment by marcelblijleven** [comment]
Hi I did not implement cucumber tests yet because I haven't used cucumber in quite some time now. It's on the todo list though

**Comment by marcelblijleven** [comment]
@lacell75 hi can you check wdio-ms-teams-service@0.1.8, I've added cucumber support

**Comment by lacell75** [comment]
Yes that works now. Thanks
